### PR TITLE
update ERROR_DISPATCH to dispatch_error

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
in favor of https://github.com/pennyphp/penny/pull/101

**Comment by fntlnz** [comment]
Thank you, waiting for penny to be released.

**Comment by gianarb** [comment]
@fntlnz is ready! :)

**Comment by samsonasik** [comment]
rebased ;)

**Comment by samsonasik** [comment]
@gianarb it uses  "gianarb/penny": "~0.5", need release first?

**Comment by gianarb** [comment]
I'm doing :D

2015-10-30 10:39 GMT+01:00 Abdul Malik Ikhsan notifications@github.com:

> @gianarb https://github.com/gianarb it uses "gianarb/penny": "~0.5",
> need release first?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pennyphp/bookshelf/pull/4#issuecomment-152473707.

## 

Gianluca Arbezzano
www.gianarb.it

**Comment by fntlnz** [comment]
Good

**Comment by gianarb** [comment]
Ready!
https://github.com/pennyphp/penny/releases/tag/0.6.0

**Comment by gianarb** [comment]
https://twitter.com/GianArb/status/660032764490682368

**Comment by fntlnz** [comment]
Thank you all!

**Pull request merged**
