### PR TITLE
update composer.json and composer.lock

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@fntlnz please verify, Thanks ;)

**Comment by fntlnz** [comment]
Thank you!
Unfortunately something broke after composer install

```
( ! ) Fatal error: Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "0" is not valid.' in /var/www/bookshelf/vendor/symfony/http-foundation/Response.php on line 454
( ! ) InvalidArgumentException: The HTTP status code "0" is not valid. in /var/www/bookshelf/vendor/symfony/http-foundation/Response.php on line 454
Call Stack
#   Time    Memory  Function    Location
1   0.0001  240584  {main}( )   .../index.php:0
2   0.0116  2314192 Penny\App->run( )   .../index.php:12
3   0.0337  4772304 Penny\App->triggerWithException( )  .../App.php:125
4   0.0337  4772392 Penny\Event\ZendEvmProxy->trigger( )    .../App.php:195
5   0.0337  4772616 Zend\EventManager\EventManager->trigger( )  .../ZendEvmProxy.php:28
6   0.0337  4773208 Zend\EventManager\EventManager->triggerListeners( ) .../EventManager.php:205
7   0.0342  4844080 call_user_func:{/var/www/bookshelf/vendor/zendframework/zend-eventmanager/src/EventManager.php:444} ( ) .../EventManager.php:444
8   0.0342  4844280 App\EventListener\DispatcherExceptionListener->onError( )   .../EventManager.php:444
9   0.0354  5031552 Symfony\Component\HttpFoundation\Response::create( )    .../DispatcherExceptionListener.php:24
10  0.0354  5031848 Symfony\Component\HttpFoundation\Response->__construct( )   .../Response.php:222
11  0.0355  5035448 Symfony\Component\HttpFoundation\Response->setStatusCode( ) .../Response.php:199
```

I can check better in a few hours, it's 4.55 am here

**Comment by samsonasik** [comment]
travis build succeed. maybe you need to composer self-update. Ok, thank you ;)

**Comment by samsonasik** [comment]
also, maybe run composer update instead.

**Comment by fntlnz** [comment]
I opened a PR about that on your fork https://github.com/samsonasik/bookshelf/pull/1

**Comment by fntlnz** [comment]
The Travis build is not very useful at the moment :(
https://github.com/pennyphp/bookshelf/issues/13

Thank you

**Pull request merged**
